// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TorrentHub.Core.Data;
using TorrentHub.Core.Enums;

#nullable disable

namespace TorrentHub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "badge_code", new[] { "early_supporter", "torrent_master", "community_contributor", "coin_collector" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ban_status", new[] { "none", "login_ban", "tracker_ban", "download_ban", "forum_ban", "messaging_ban", "invite_ban" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "forum_category_code", new[] { "announcement", "general", "feedback", "invite", "watering" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "report_reason", new[] { "illegal_content", "misleading_category", "low_quality", "duplicate", "dead_torrent", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "request_status", new[] { "pending", "filled", "pending_confirmation", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "store_item_code", new[] { "upload_credit10gb", "upload_credit50gb", "invite_one", "invite_five", "double_upload", "no_hit_and_run", "badge" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "torrent_category", new[] { "movie", "documentary", "series", "animation", "game", "music", "variety", "sports", "concert", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "torrent_sticky_status", new[] { "none", "official_sticky", "user_sticky" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "mosquito", "user", "power_user", "elite_user", "crazy_user", "veteran_user", "vip", "uploader", "seeder", "moderator", "administrator" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TorrentHub.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("TorrentHub.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<BadgeCode>("Code")
                        .HasColumnType("badge_code");

                    b.HasKey("Id");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("TorrentHub.Entities.BannedClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserAgentPrefix")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("BannedClients");
                });

            modelBuilder.Entity("TorrentHub.Entities.CheatLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CheatLogs");
                });

            modelBuilder.Entity("TorrentHub.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TorrentId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TorrentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TorrentHub.Entities.ForumCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<ForumCategoryCode>("Code")
                        .HasColumnType("forum_category_code");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ForumCategories");
                });

            modelBuilder.Entity("TorrentHub.Entities.ForumPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TopicId");

                    b.ToTable("ForumPosts");
                });

            modelBuilder.Entity("TorrentHub.Entities.ForumTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSticky")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastPostTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ForumTopics");
                });

            modelBuilder.Entity("TorrentHub.Entities.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GeneratorUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GeneratorUserId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("TorrentHub.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReceiverDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<bool>("SenderDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TorrentHub.Entities.Peers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Downloaded")
                        .HasColumnType("numeric(20,0)");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet");

                    b.Property<bool>("IsSeeder")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastAnnounce")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("TorrentId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Uploaded")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TorrentId");

                    b.HasIndex("UserId");

                    b.ToTable("Peers");
                });

            modelBuilder.Entity("TorrentHub.Entities.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Options")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("TorrentHub.Entities.PollVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PollId")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedOption")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("VotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PollId", "UserId")
                        .IsUnique();

                    b.ToTable("PollVotes");
                });

            modelBuilder.Entity("TorrentHub.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProcessedByUserId")
                        .HasColumnType("integer");

                    b.Property<ReportReason>("Reason")
                        .HasColumnType("report_reason");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReporterUserId")
                        .HasColumnType("integer");

                    b.Property<int>("TorrentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedByUserId");

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("TorrentId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("TorrentHub.Entities.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BountyAmount")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset?>("ConfirmationDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("FilledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FilledByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("FilledWithTorrentId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("integer");

                    b.Property<RequestStatus>("Status")
                        .HasColumnType("request_status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FilledByUserId");

                    b.HasIndex("FilledWithTorrentId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("TorrentHub.Entities.SiteSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Key");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("TorrentHub.Entities.StoreItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BadgeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<StoreItemCode>("ItemCode")
                        .HasColumnType("store_item_code");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.ToTable("StoreItems");
                });

            modelBuilder.Entity("TorrentHub.Entities.Torrent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackdropPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Cast")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<TorrentCategory>("Category")
                        .HasColumnType("torrent_category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeleteReason")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Directors")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("FreeUntil")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<byte[]>("InfoHash")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("bytea");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean");

                    b.Property<int>("Leechers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int?>("Runtime")
                        .HasColumnType("integer");

                    b.Property<int>("Seeders")
                        .HasColumnType("integer");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<int>("Snatched")
                        .HasColumnType("integer");

                    b.Property<TorrentStickyStatus>("StickyStatus")
                        .HasColumnType("torrent_sticky_status");

                    b.Property<int?>("TMDbId")
                        .HasColumnType("integer");

                    b.Property<string>("Tagline")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InfoHash")
                        .IsUnique();

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Torrents");
                });

            modelBuilder.Entity("TorrentHub.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("BanReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<BanStatus>("BanStatus")
                        .HasColumnType("ban_status");

                    b.Property<DateTimeOffset?>("BanUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CheatWarningCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Coins")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DoubleUploadExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DownloadedBytes")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("InviteId")
                        .HasColumnType("uuid");

                    b.Property<long>("InviteNum")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDoubleUploadActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNoHRActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset?>("NoHRExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NominalDownloadedBytes")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("NominalUploadedBytes")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid>("Passkey")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role");

                    b.Property<Guid>("RssKey")
                        .HasColumnType("uuid");

                    b.Property<string>("Signature")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("TotalLeechingTimeMinutes")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("TotalSeedingTimeMinutes")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UploadedBytes")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("InviteId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TorrentHub.Entities.UserBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BadgeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("TorrentHub.Entities.UserDailyStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentBonusesGiven")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("UserDailyStats");
                });

            modelBuilder.Entity("TorrentHub.Entities.Announcement", b =>
                {
                    b.HasOne("TorrentHub.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("TorrentHub.Entities.CheatLog", b =>
                {
                    b.HasOne("TorrentHub.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TorrentHub.Entities.Comment", b =>
                {
                    b.HasOne("TorrentHub.Entities.Torrent", "Torrent")
                        .WithMany()
                        .HasForeignKey("TorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorrentHub.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torrent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TorrentHub.Entities.ForumPost", b =>
                {
                    b.HasOne("TorrentHub.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TorrentHub.Entities.ForumTopic", "Topic")
                        .WithMany("Posts")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("TorrentHub.Entities.ForumTopic", b =>
                {
                    b.HasOne("TorrentHub.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TorrentHub.Entities.ForumCategory", "Category")
                        .WithMany("Topics")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TorrentHub.Entities.Invite", b =>
                {
                    b.HasOne("TorrentHub.Entities.User", "GeneratorUser")
                        .WithMany("GeneratedInvites")
                        .HasForeignKey("GeneratorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GeneratorUser");
                });

            modelBuilder.Entity("TorrentHub.Entities.Message", b =>
                {
                    b.HasOne("TorrentHub.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorrentHub.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("TorrentHub.Entities.Peers", b =>
                {
                    b.HasOne("TorrentHub.Entities.Torrent", "Torrent")
                        .WithMany()
                        .HasForeignKey("TorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorrentHub.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torrent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TorrentHub.Entities.PollVote", b =>
                {
                    b.HasOne("TorrentHub.Entities.Poll", "Poll")
                        .WithMany("Votes")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorrentHub.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TorrentHub.Entities.Report", b =>
                {
                    b.HasOne("TorrentHub.Entities.User", "ProcessedByUser")
                        .WithMany()
                        .HasForeignKey("ProcessedByUserId");

                    b.HasOne("TorrentHub.Entities.User", "ReporterUser")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorrentHub.Entities.Torrent", "Torrent")
                        .WithMany()
                        .HasForeignKey("TorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessedByUser");

                    b.Navigation("ReporterUser");

                    b.Navigation("Torrent");
                });

            modelBuilder.Entity("TorrentHub.Entities.Request", b =>
                {
                    b.HasOne("TorrentHub.Entities.User", "FilledByUser")
                        .WithMany()
                        .HasForeignKey("FilledByUserId");

                    b.HasOne("TorrentHub.Entities.Torrent", "FilledWithTorrent")
                        .WithMany()
                        .HasForeignKey("FilledWithTorrentId");

                    b.HasOne("TorrentHub.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilledByUser");

                    b.Navigation("FilledWithTorrent");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("TorrentHub.Entities.StoreItem", b =>
                {
                    b.HasOne("TorrentHub.Entities.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId");

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("TorrentHub.Entities.Torrent", b =>
                {
                    b.HasOne("TorrentHub.Entities.User", "UploadedByUser")
                        .WithMany("Torrents")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("TorrentHub.Entities.User", b =>
                {
                    b.HasOne("TorrentHub.Entities.Invite", "Invite")
                        .WithOne("UsedByUser")
                        .HasForeignKey("TorrentHub.Entities.User", "InviteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Invite");
                });

            modelBuilder.Entity("TorrentHub.Entities.UserBadge", b =>
                {
                    b.HasOne("TorrentHub.Entities.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorrentHub.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TorrentHub.Entities.UserDailyStats", b =>
                {
                    b.HasOne("TorrentHub.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TorrentHub.Entities.ForumCategory", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("TorrentHub.Entities.ForumTopic", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("TorrentHub.Entities.Invite", b =>
                {
                    b.Navigation("UsedByUser");
                });

            modelBuilder.Entity("TorrentHub.Entities.Poll", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("TorrentHub.Entities.User", b =>
                {
                    b.Navigation("GeneratedInvites");

                    b.Navigation("Torrents");
                });
#pragma warning restore 612, 618
        }
    }
}

