// <auto-generated/>
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sakura.PT.DTOs;
using Sakura.PT.Enums;
using Sakura.PT.Services;

namespace Sakura.PT.Controllers;

/// <summary>
/// API Controller for managing user requests (bounties).
/// All endpoints require user authentication.
/// </summary>
[ApiController]
[Route("api/[controller]")]
[Authorize]
public class RequestController : ControllerBase
{
    private readonly IRequestService _requestService;
    private readonly ILogger<RequestController> _logger;

    public RequestController(IRequestService requestService, ILogger<RequestController> logger)
    {
        _requestService = requestService;
        _logger = logger;
    }

    /// <summary>
    /// Creates a new request (bounty).
    /// </summary>
    /// <param name="createRequestDto">The DTO containing the title, description, and initial bounty amount for the request.</param>
    /// <returns>The created request object if successful.</returns>
    [HttpPost("create")]
    public async Task<IActionResult> CreateRequest([FromBody] CreateRequestDto createRequestDto)
    {
        // 从 JWT Token 中获取当前登录用户的 ID
        var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier) ?? throw new InvalidOperationException("User ID claim not found."));
        var (success, message, request) = await _requestService.CreateRequestAsync(createRequestDto, userId);

        if (!success)
        {
            _logger.LogWarning("Failed to create request: {Message}", message);
            return BadRequest(message);
        }

        return Ok(request);
    }

    /// <summary>
    /// Adds bounty (SakuraCoins) to an existing request.
    /// </summary>
    /// <param name="requestId">The ID of the request to add bounty to.</param>
    /// <param name="amount">The amount of SakuraCoins to add.</param>
    /// <returns>A success message.</returns>
    [HttpPost("{requestId}/addBounty")]
    public async Task<IActionResult> AddBounty(int requestId, [FromForm] ulong amount)
    {
        var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier) ?? throw new InvalidOperationException("User ID claim not found."));
        var (success, message) = await _requestService.AddBountyAsync(requestId, amount, userId);

        if (!success)
        {
            _logger.LogWarning("Failed to add bounty: {Message}", message);
            return BadRequest(message);
        }

        return Ok(new { message = message });
    }

    /// <summary>
    /// Gets a list of requests, filterable by status.
    /// </summary>
    /// <param name="status">The status to filter by (Pending, Filled, Expired). Defaults to Pending.</param>
    /// <returns>A list of request objects.</returns>
    [HttpGet]
    public async Task<IActionResult> GetRequests([FromQuery] RequestStatus? status)
    {
        // 如果调用方没有提供 status，则默认为 Pending
        var requests = await _requestService.GetRequestsAsync(status ?? RequestStatus.Pending);
        return Ok(requests);
    }

    /// <summary>
    /// Fills a request with a specific torrent.
    /// </summary>
    /// <param name="requestId">The ID of the request to fill.</param>
    /// <param name="torrentId">The ID of the torrent that fulfills the request.</param>
    /// <returns>A success message.</returns>
    [HttpPost("{requestId}/fill/{torrentId}")]
    public async Task<IActionResult> FillRequest(int requestId, int torrentId)
    {
        var fillerUserId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier) ?? throw new InvalidOperationException("User ID claim not found."));
        var (success, message) = await _requestService.FillRequestAsync(requestId, torrentId, fillerUserId);

        if (!success)
        {
            _logger.LogWarning("Failed to fill request: {Message}", message);
            return BadRequest(message);
        }

        return Ok(new { message = message });
    }
}
